DROP TABLE IF EXISTS Localitzacio;
DROP TABLE IF EXISTS Ciutat;
DROP TABLE IF EXISTS Hotel;

CREATE TABLE IF NOT EXISTS Hotel (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom TEXT NOT NULL,
    Estels INTEGER NOT NULL,
    Adress TEXT NOT NULL,
    Telefon INTEGER NOT NULL,
    HabitacionSimple INTEGER NOT NULL,
    HabitacionsDobles INTEGER NOT NULL,
	DataInaguracio TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS Ciutat (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Localitzacio (
	idCiutat INTEGER PRIMARY KEY,
    idHotel INTEGER NOT NULL,
    FOREIGN KEY ( IdCiutat ) REFERENCES Ciutat ( Id ),
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id )
);
