DROP TABLE IF EXISTS Localitzacio;
DROP TABLE IF EXISTS Ciutat;
DROP TABLE IF EXISTS Hotel;

CREATE TABLE IF NOT EXISTS Hotel (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom TEXT NOT NULL,
    Estels INTEGER NOT NULL,
    Adress TEXT NOT NULL,
    Telefon INTEGER NOT NULL,
    HSimple INTEGER NOT NULL,
    HDoble INTEGER NOT NULL,
	DataInaguracio TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DePlatja (
	IdHotel INTEGER PRIMARY KEY,
	PlatjaPrivada INTEGER NOT NULL,
	ServeiEmbarcacions INTEGER NOT NULL,
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS DeMuntanya (
	IdHotel INTEGER PRIMARY KEY,
	Piscina INTEGER NOT NULL,
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS Activitat (
	Nom TEXT PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS NivellQualitat (
	IdHotel INTEGER PRIMARY KEY,
	Valor INTEGER NOT NULL,
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS Ciutat (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom TEXT NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS Localitzacio (
	idCiutat INTEGER PRIMARY KEY,
    idHotel INTEGER NOT NULL,
    FOREIGN KEY ( IdCiutat ) REFERENCES Ciutat ( Id ),
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS CadenaHotelera (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    AdressFiscal TEXT NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS Pertany (
    IdHotel INTEGER NOT NULL,
    IdCadena INTEGER NOT NULL,
    PRIMARY_KEY( IdHotel, IdCadena ),
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id ),
    FOREIGN KEY ( IdCadena ) REFERENCES CadenaHotelera ( Id )
);

CREATE TABLE IF NOT EXISTS Empleat ( 
    CI INTEGER PRIMARY KEY,
    Nom TEXT NOT NULL,
    Cognom TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS Director (
	CI INTEGER NOT NULL UNIQUE,
	Id INTEGER NOT NULL UNIQUE,
	PRIMARY_KEY ( CI, Id ),
	FOREIGN KEY ( CI ) REFERENCES Empleat ( CI ),
	FOREIGN KEY ( Id ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS Antiguitat (
	CI INTEGER NOT NULL,
	Id INTEGER NOT NULL,
	PRIMARY_KEY( CI, Id ),
	FOREIGN KEY ( CI ) REFERENCES Empleat ( CI ),
	FOREIGN KEY ( Id ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS Actual (
	CI INTEGER NOT NULL UNIQUE,
	Id INTEGER NOT NULL UNIQUE,
	PRIMARY_KEY ( CI, Id ),
	FOREIGN KEY ( CI ) REFERENCES Empleat ( CI ),
	FOREIGN KEY ( Id ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS Contractacio (
	CI INTEGER PRIMARY KEY,
	Id INTEGER NOT NULL,
	FOREIGN KEY ( CI ) REFERENCES Empleat ( CI ),
	FOREIGN KEY ( Id ) REFERENCES CadenaHotelera ( Id )
);


CREATE TABLE IF NOT EXISTS Agencia (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Nom TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS AssignacioTurista (
	IdHotel INTEGER NOT NULL,
	IdAgencia INTEGER NOT NULL,
	PRIMARY KEY ( IdHotel, IdAgencia ),
	FOREIGN KEY ( IdAgencia ) REFERENCES Agencia ( Id ),
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id )
);


CREATE TABLE IF NOT EXISTS Turista (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Year INTEGER NOT NULL,
	Mes INTEGER NOT NULL,
	Valor INTEGER NOT NULL
 );

CREATE TABLE IF NOT EXISTS Assignacio (
	IdTurista INTEGER PRIMARY KEY,
	IdHotel INTEGER NOT NULL,
	IdAgencia INTEGER NOT NULL,
	FOREIGN KEY ( IdAgencia ) REFERENCES Agencia ( Id ),
	FOREIGN KEY ( IdHotel ) REFERENCES Hotel ( Id ),
	FOREIGN KEY ( IdTurista ) REFERENCES Turista ( Id )
);

CREATE TABLE IF NOT EXISTS Categoria (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Nom TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Delegacio (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Direccio TEXT NOT NULL,
	Fax INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Obtencio (
	idAgencia INTEGER NOT NULL,
	idCategoria INTEGER NOT NULL,
	PRIMARY KEY ( idAgencia, idCategoria ),
	FOREIGN KEY ( IdAgencia ) REFERENCES Agencia ( id ),
	FOREIGN KEY ( IdCategoria ) REFERENCES Categoria ( id )
);

CREATE TABLE IF NOT EXISTS Conformacio (
	idDelegacio INTEGER PRIMARY KEY,
	idAgencia INTEGER NOT NULL,
	FOREIGN KEY ( idDelegacio ) REFERENCES Delegacio ( id )
	FOREIGN KEY ( idAgencia ) REFERENCES Agencia ( id )
);


